// <auto-generated />
using System;
using Assignment_1.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_1.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Assignment_1.Entities.Student", b =>
            {
                b.Property<int>("StudentID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                b.Property<int?>("Age")
                    .HasColumnType("int");

                b.Property<string>("DateOfBirth")
                    .HasColumnType("nvarchar(10)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double?>("GPA")
                    .IsRequired()
                    .HasColumnType("float");

                b.Property<string>("GpaScale")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("StudentID");

                b.ToTable("Students");

                b.HasData(
                    new
                    {
                        StudentID = 1,
                        DateOfBirth = "05/31/1971",
                        FirstName = "Bart",
                        GPA = 2.7000000000000002,
                        LastName = "Simpson"
                    },
                    new
                    {
                        StudentID = 2,
                        DateOfBirth = "08/05/1973",
                        FirstName = "Lisa",
                        GPA = 4.0,
                        LastName = "Simpson"
                    });
            });
#pragma warning restore 612, 618
        }
    }
}
